// Byte-exact comparison of SimEngine's shared C++ renderer against firmware
// reference vectors generated by test/VectorGen.cpp.

import { test, assert, assertEqual } from '../harness.js';
import { SimEngine } from '../../js/engine.js';
import { DEFAULT_SEEDS } from '../../js/renderer.js';

const vectorsUrl = new URL('../vectors/reference.json', import.meta.url);
let vectors;
if (typeof process !== 'undefined' && process.versions?.node) {
  const { readFile } = await import('node:fs/promises');
  vectors = JSON.parse(await readFile(vectorsUrl, 'utf8'));
} else {
  vectors = await (await fetch(vectorsUrl)).json();
}

test('vector meta seeds match the shared renderer defaults', () => {
  const engine = new SimEngine({ devices: ['scarf'], paused: true });
  for (const [name, value] of Object.entries(vectors.meta.effectSeeds)) {
    assertEqual(DEFAULT_SEEDS[name], value, `default seed for ${name}`);
    assertEqual(engine.registry.seeds[name], value, `engine seed for ${name}`);
  }
});

test('firmware effect table matches shared C++ metadata', () => {
  const effects = new SimEngine({ paused: true }).listEffects();
  assertEqual(effects.length, vectors.effects.length, 'wire table size');
  for (const { index, name } of vectors.effects) {
    assertEqual(effects[index].name, name, `effect index ${index}`);
  }
});

test('firmware palette table matches shared C++ metadata', () => {
  const palettes = new SimEngine({ paused: true }).listPalettes();
  assertEqual(palettes.length, vectors.palettes.length, 'palette count');
  for (const { index, name } of vectors.palettes) {
    assertEqual(palettes[index].name, name, `palette index ${index}`);
  }
});

test('every reference case renders byte-identically through SimEngine', () => {
  const engines = new Map();
  const failures = [];
  for (const [caseIndex, vectorCase] of vectors.cases.entries()) {
    if (!engines.has(vectorCase.device)) {
      engines.set(vectorCase.device, new SimEngine({
        devices: [vectorCase.device], paused: true,
      }));
    }
    const engine = engines.get(vectorCase.device);
    engine.clearControl();
    if (vectorCase.control) {
      engine.setControl(vectorCase.control.rgb, 0);
    } else {
      engine.setEffect(vectorCase.effectIndex)
        .setPalette(vectorCase.paletteIndex);
    }
    engine.setTime(vectorCase.timeMs);
    const leds = engine.getSnapshot().devices[0].strips
      .flatMap((strip) => strip.leds);
    if (JSON.stringify(leds) !== JSON.stringify(vectorCase.leds)) {
      let firstBad = 0;
      while (firstBad < vectorCase.leds.length &&
             JSON.stringify(leds[firstBad]) ===
               JSON.stringify(vectorCase.leds[firstBad])) {
        firstBad++;
      }
      failures.push(
        `case ${caseIndex} (${vectorCase.device}, t=${
          vectorCase.timeMs}) LED ${firstBad}: expected ${
          JSON.stringify(vectorCase.leds[firstBad])}, got ${
          JSON.stringify(leds[firstBad])}`,
      );
    }
  }
  assert(
    failures.length === 0,
    `${failures.length}/${vectors.cases.length} cases mismatched:\n` +
      failures.slice(0, 20).join('\n'),
  );
});
