// Covers FR-005/FR-020, SC-003: byte-exact comparison of the JS engine
// against firmware reference vectors generated by test/VectorGen.cpp
// (see specs/001-web-simulator/contracts/reference-vectors.md).

import { test, assert, assertEqual, assertDeepEqual } from '../harness.js';
import { SimEngine } from '../../js/engine.js';
import { DEFAULT_FIREFLY_OFFSET } from '../../js/effects/registry.js';
import {
  cubicwave8, ease8InOutApprox, hsv2rgbRainbow, resetRandom16, random16,
  scale8, sin16, sin8,
} from '../../js/fastled.js';

const vectorsUrl = new URL('../vectors/reference.json', import.meta.url);
let vectors;
if (typeof process !== 'undefined' && process.versions?.node) {
  const { readFile } = await import('node:fs/promises');
  vectors = JSON.parse(await readFile(vectorsUrl, 'utf8'));
} else {
  vectors = await (await fetch(vectorsUrl)).json();
}

test('vector meta seeds match the registry defaults', () => {
  const engine = new SimEngine({ devices: ['scarf'], paused: true });
  for (const [name, value] of Object.entries(vectors.meta.effectSeeds)) {
    assertEqual(engine.registry.seeds[name], value,
      `seed for ${name} (is DEFAULT_FIREFLY_OFFSET=${
        DEFAULT_FIREFLY_OFFSET} stale?)`);
  }
});

test('firmware effect table matches the JS wire table', () => {
  const engine = new SimEngine({ devices: ['scarf'], paused: true });
  const js = engine.listEffects();
  assertEqual(js.length, vectors.effects.length, 'wire table size');
  for (const { index, name } of vectors.effects) {
    assertEqual(js[index].name, name, `effect index ${index}`);
  }
});

test('firmware palette table matches the JS palettes', () => {
  const engine = new SimEngine({ devices: ['scarf'], paused: true });
  const js = engine.listPalettes();
  assertEqual(js.length, vectors.palettes.length, 'palette count');
  for (const { index, name } of vectors.palettes) {
    assertEqual(js[index].name, name, `palette index ${index}`);
  }
});

test('math primitives match the firmware build', () => {
  const p = vectors.primitives;
  for (const [fn, samples] of [[sin16, p.sin16], [sin8, p.sin8],
    [cubicwave8, p.cubicwave8],
    [ease8InOutApprox, p.ease8InOutApprox]]) {
    for (const sample of samples) {
      assertEqual(fn(sample.in), sample.out, `${fn.name}(${sample.in})`);
    }
  }
  for (const sample of p.scale8) {
    assertEqual(scale8(sample.i, sample.scale), sample.out,
      `scale8(${sample.i},${sample.scale})`);
  }
  for (const { h, s, v, out } of p.hsv2rgbRainbow) {
    const rgb = hsv2rgbRainbow({ h, s, v });
    assertDeepEqual(
      [rgb.r, rgb.g, rgb.b], out, `hsv2rgbRainbow(${h},${s},${v})`);
  }
  resetRandom16();
  assertDeepEqual([...Array(5)].map(() => random16()), p.random16First5,
    'random16 sequence from seed 1337');
});

test('every reference case renders byte-identically', () => {
  // One engine per device, reused across cases (effects are stateless between
  // renders; the registry seeds are construction-time only).
  const engines = new Map();
  const failures = [];
  for (const [caseIndex, c] of vectors.cases.entries()) {
    if (!engines.has(c.device)) {
      engines.set(c.device,
        new SimEngine({ devices: [c.device], paused: true }));
    }
    const engine = engines.get(c.device);
    engine.clearControl();
    if (c.control) {
      engine.setControl(c.control.rgb, 0);
    } else {
      engine.setEffect(c.effectIndex).setPalette(c.paletteIndex);
    }
    engine.setTime(c.timeMs);
    const snapshot = engine.getSnapshot();
    const leds = snapshot.devices[0].strips.flatMap((s) => s.leds);
    if (JSON.stringify(leds) !== JSON.stringify(c.leds)) {
      const label = c.control ?
        `control[${c.control.rgb}]` :
        `effect ${c.effectIndex} palette ${c.paletteIndex}`;
      let firstBad = 0;
      while (firstBad < c.leds.length &&
             JSON.stringify(leds[firstBad]) ===
                 JSON.stringify(c.leds[firstBad])) {
        firstBad++;
      }
      failures.push(`case ${caseIndex} (${label}, ${c.device}, t=${
        c.timeMs}): led ${firstBad} expected ${
        JSON.stringify(c.leds[firstBad])} got ${
        JSON.stringify(leds[firstBad])}`);
    }
  }
  assert(failures.length === 0,
    `${failures.length}/${vectors.cases.length} cases mismatched:\n` +
             failures.slice(0, 20).join('\n') +
             (failures.length > 20 ? '\n…' : ''));
});
