M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date Sun 30 Jul 2023 10:17:11 AM MDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-30T10:17:11-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X54.0Y-88.32
X54.0Y-90.86
X54.0Y-93.4
T2
X89.5Y-108.5
T0
M30
