M48
; DRILL file {KiCad 6.0.5-a6ca702e91~116~ubuntu20.04.1} date Wed 29 Jun 2022 10:36:19 PM MDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-29T22:36:19-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.5-a6ca702e91~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X72.46Y-100.1
X75.0Y-100.1
X77.54Y-100.1
T2
X30.3Y-98.0
X83.2Y-97.8
X83.5Y-68.0
T0
M30
